export const validationMessage = {
  required: () => "O campo é obrigatório.",
  min6Char: () => "Mínimo de 6 caracteres.",
  validEmail: () => "Por favor, insira um e-mail válido.",
  requiredEmail: () => "Por favor, preencha o campo Email.",
  requiredPassword: () => "Por favor, preencha o campo Senha.",
  requiredName: () => "Por favor, preencha o campo Nome.",
  requiredPhone: () => "Por favor, preencha o campo Telefone.",
  requiredRazaoSocial: () => "Por favor, preencha o campo Razão Social.",
  requiredCEP: () => 'Por favor, preencha o campo de CEP',
  requiredCPF: () => "Por favor, preencha o campo de CPF.",
  requiredCNPJ: () => "Por favor, preencha o campo de CNPJ.",
  requiredBirthDay: () => "Por favor, preencha o campo Data de Aniversário.",
  requiredPasswordsMustMatch: () => "Confirmação incorreta de senha incorreta.",
};
